create table
    public.users
(
    user_id             bigint generated by default as identity,
    google_user_id      character varying        not null,
    username            character varying        not null,
    email               character varying        not null,
    profile_picture_url character varying null,
    locale              character varying null,
    updated_at          timestamp with time zone null default (now() at time zone 'utc'::text),
    created_at          timestamp with time zone not null default (now() at time zone 'utc'::text),
    first_name          character varying(255) null,
    last_name           character varying(255) null,
    constraint users_pkey primary key (user_id),
    constraint users_email_key unique (email),
    constraint users_google_user_id_key unique (google_user_id),
    constraint users_username_key unique (username)
) tablespace pg_default;

create table
    public.topics
(
    topic_id   bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    topic_name character varying        not null,
    constraint topics_pkey primary key (topic_id),
    constraint topics_topic_name_key unique (topic_name)
) tablespace pg_default;

create table
    public.preferences
(
    preference_id bigint generated by default as identity,
    topic_id      bigint null,
    user_id       bigint null,
    created_at    timestamp with time zone not null default (now() at time zone 'utc'::text),
    score         bigint                   not null default '0'::bigint,
    constraint preferences_pkey primary key (preference_id),
    constraint preferences_preference_id_key unique (preference_id),
    constraint preferences_topic_id_fkey foreign key (topic_id) references topics (topic_id),
    constraint preferences_user_id_fkey foreign key (user_id) references users (user_id)
) tablespace pg_default;

create table
    public.posts
(
    post_id    bigint generated by default as identity,
    user_id    bigint                   not null,
    content    text                     not null,
    created_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    updated_at timestamp with time zone null,
    topic_id   bigint null,
    constraint posts_pkey primary key (post_id),
    constraint posts_topic_id_fkey foreign key (topic_id) references topics (topic_id) on delete set default,
    constraint posts_user_id_fkey foreign key (user_id) references users (user_id)
) tablespace pg_default;

create table
    public.likes
(
    post_id    bigint not null,
    user_id    bigint not null,
    created_at timestamp with time zone null default (now() at time zone 'utc'::text),
    like_id    bigint generated by default as identity,
    constraint likes_pkey primary key (like_id),
    constraint likes_like_id_key unique (like_id),
    constraint likes_post_id_fkey foreign key (post_id) references posts (post_id) on delete cascade,
    constraint likes_user_id_fkey foreign key (user_id) references users (user_id) on delete cascade
) tablespace pg_default;